config/routes.rb
Zing::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "pages/about" => "pages#about", :as => "pages/about"
  get 'pages/home'     => "pages#home", :as => "pages/home"
  get 'pages/help'
  get 'users/new'
  get 'posts/create' => "posts#create", :as => "posts_create"
  get 'posts/create'
  get 'posts/destroy'
  get 'posts/new'
  get 'sessions/new'

  get "sign_out" => "sessions#destroy", :as => "sign_out"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match '/sign_up',  to: 'users#new'
  match '/help',    to: 'pages#help'
  match '/about',   to: 'pages#about'
  match '/home', to: 'pages#home'

   root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :password, :password_confirmation, :username

  attr_accessor :password
  before_save :encrypt_password

  has_many :posts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
           class_name: "Relationship",
           dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  before_save :create_remember_token

  #validates_confirmation_of :password
  #validates_presence_of :password, :on => :create
  #validates_presence_of :password_confirmation
  #validates_presence_of :email
  #validates_uniqueness_of :email
  #validates_presence_of :username
  #validates_uniqueness_of :username

  validates :username,
            :presence => true,
            :length => {:within => 4..20}


  validates :email,
            :uniqueness => true,
            :length => {:within => 5..40},
            :format => {:with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}

  validates :password,
            :confirmation => true,
            :length => {:within => 6..20},
            :presence => true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def feed
    Post.from_users_followed_by(self)
  end


  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: [:index, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        format.html { redirect_to @user, notice: 'Your account was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Your details successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to log_in_url, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/users/  _follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <form accept-charset="UTF-8" action="/users" class="new_user" id="new_user" method="post">

      <div class="field">
      <label for="user_username"></label>
        <input id="user_username" name="user[username]" size="30" type="text" placeholder="Username" />
      </div>

      <div class="field">
      <label for="user_email"></label>
      <input id="user_email" name="user[email]" type="text" size="30" placeholder="Email" />
    </div>

      <div class="field">
      <label for="user_password"></label>
      <input id="user_password" name="user[password]" size="30" type="password" placeholder="Your Password" />
    </div>

      <div class="field">
      <label for="user_password_confirmation"></label>
      <input id="user_password_confirmation" name="user[password_confirmation]" size="30" type="password"
             placeholder="Password confirmation" />
    </div>

    <div class="sign_up button">
      <input class="btn btn-large btn-primary" name="commit" type="submit" value="Sign up for Zing"/>
    </div>

        </form>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update accounts details</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <form accept-charset="UTF-8" action="/users" class="new_user" id="new_user" method="post">

      <div class="field">
        <label for="user_username"></label>
        <input id="user_username" name="user[username]" size="30" type="text" placeholder="Username" />
      </div>

      <div class="field">
        <label for="user_email"></label>
        <input id="user_email" name="user[email]" type="text" size="30" placeholder="Email" />
      </div>

      <div class="field">
        <label for="user_password"></label>
        <input id="user_password" name="user[password]" size="30" type="password" placeholder="Your Password" />
      </div>

      <div class="field">
        <label for="user_password_confirmation"></label>
        <input id="user_password_confirmation" name="user[password_confirmation]" size="30" type="password"
               placeholder="Password confirmation" />
      </div>

      <div class="sign_up button">
        <input class="btn btn-large btn-primary" name="commit" type="submit" value="update"/>
      </div>

      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">change</a>

    </form>

<% end %>



<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>New to Zing! Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
    <% if @user.posts.any? %>
        <h3>Posts (<%= @user.posts.count %>)</h3>
        <ol class="posts">
          <%= render @posts %>
        </ol>

        <%= will_paginate @posts %>
    <% end %>
  </div>
</div>

 <%= link_to 'Post', new_post_path %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_follow.html.erb .erb
<%= provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Posts:</b> <%= @user.posts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30), user %>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>