config/routes.rb
Zing::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "pages/about" => "pages#about", :as => "pages/about"
  get 'pages/home'     => "pages#home", :as => "pages/home"
  get 'pages/help'
  get 'users/new'
  get 'posts/create' => "posts#create", :as => "posts_create"
  get 'posts/create'
  get 'posts/destroy'
  get 'posts/new'
  get 'sessions/new'

  get "sign_out" => "sessions#destroy", :as => "sign_out"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match '/sign_up',  to: 'users#new'
  match '/help',    to: 'pages#help'
  match '/about',   to: 'pages#about'
  match '/home', to: 'pages#home'

   root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

    <div id="error_explanation">

      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="posts">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
      <%= link_to "delete", feed_item, method: :delete,
                  confirm: "You sure?",
                  title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_post_form.html.erb
<%= form_for(@posts) do |f| %>
    <%= render 'shared/error_messages', object: @post %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new post..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1><%= current_user.username %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>