config/routes.rb
Zing::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "pages/about" => "pages#about", :as => "pages/about"
  get 'pages/home'     => "pages#home", :as => "pages/home"
  get 'pages/help'
  get 'users/new'
  get 'posts/create' => "posts#create", :as => "posts_create"
  get 'posts/create'
  get 'posts/destroy'
  get 'posts/new'
  get 'sessions/new'

  get "sign_out" => "sessions#destroy", :as => "sign_out"
  get "sign_in" => "sessions#new", :as => "sign_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match '/sign_up',  to: 'users#new'
  match '/help',    to: 'pages#help'
  match '/about',   to: 'pages#about'
  match '/home', to: 'pages#home'

   root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer" xmlns="http://www.w3.org/1999/html">
  <small>


  </small>
  <nav>
    <p>
      <%= link_to "About us", '/pages/about' %>
      <%= link_to "Help", '/pages/help' %>
      <%= link_to "Home", '/pages/home' %>
    </p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="zing-tag">
  <div class="zing-menu">
    <%= link_to "Zing", '/pages/home' %>

      <ul id="nav">
        <li><%= link_to "Home", '/pages/home' %></li>
        <li><%= link_to "Help", '/pages/help' %></li>
        <% if signed_in? %>
            <li><%= link_to "Post", posts_new_path(current_user) %></li>
            <li><%= link_to "Users", '/users/index(current_user)' %></li>
            <li>

              <a href="#"> Account </a>
              <ul>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path %></li>
                <li> <%= link_to "Sign out", sign_out_path %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign in", sign_in_path %></li>
        <% end %>
      </ul>

  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zing</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
    <p id="alert"><%= alert %></p>



<%= yield %>


</div>
<%= render 'layouts/footer' %>
</body>
</html>